# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Jupyter notebooks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}
      MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Set up Java (required for algorithms/nlp-basics.ipynb)
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install pytest pytest-xdist nbmake
      - name: mplcursors (required for tools/spacy.ipynb as installation from notebook fails on Github)
        run: pip install -U mplcursors # ipympl not required here
      - name: Test algorithms
        run: pytest --nbmake --nbmake-timeout=1000 -n=auto algorithms
      - name: Test tools
        run: pytest --nbmake --nbmake-timeout=1000 -n=auto tools
      - name: Test use cases
        run: pytest --nbmake --nbmake-timeout=1000 -n=auto use-cases        
